dist: trusty
sudo: true

cache:
  directories:
  - $HOME/.m2

language: java
jdk:
  - oraclejdk8
  - openjdk8

install: true

script: "sudo sh tools/mvn_script.sh"
after_success:
  - bash <(curl -s https://codecov.io/bash)
